[tool.pylint."MESSAGES CONTROL"]

max-line-length = 120
disable = """
    missing-timeout,
    missing-module-docstring,
    missing-function-docstring,
    missing-class-docstring,
    consider-using-f-string,
    unused-argument,
    too-few-public-methods,
    invalid-name,
    line-too-long,
    redefined-outer-name,
    missing-module-docstring,
    import-error
"""

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true
