apiVersion: 1

datasources:
  - name: Postgres Connection DB
    type: postgres
    access: proxy
    url: db:5432
    database: postgres
    user: postgres
    secureJsonData:
        password: 'example'
    jsonData:
        sslmode: 'disable'
